name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependencias
        run: dotnet restore TDD.sln

      - name: Compilar proyecto
        run: dotnet build TDD.sln --no-restore

      - name: Ejecutar pruebas
        run: dotnet test TDD.sln --no-build
